# Generated by Django 4.0.5 on 2022-11-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blog_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
