# Generated by Django 4.0.5 on 2022-11-06 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(default='Mehjabin chowdhury', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('qoutes', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='images')),
                ('category', models.CharField(blank=True, choices=[('travel', 'travel'), ('fashion', 'fashion'), ('food', 'food'), ('science', 'science')], default='travel', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
