# Generated by Django 4.0.5 on 2022-11-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
