# Generated by Django 4.0.5 on 2022-11-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, choices=[('travel', 'travel'), ('travel', 'travel'), ('travel', 'travel'), ('travel', 'travel')], max_length=10),
        ),
    ]
