# Generated by Django 4.0.5 on 2022-11-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='qoutes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, choices=[('travel', 'travel'), ('fashion', 'fashion'), ('food', 'food'), ('science', 'science')], default='travel', max_length=10),
        ),
    ]
